status="ToDo"
schedule="Instant"
id=4
loopk=0
fail_task_id=1000
fail_job_id=1000
active=true

[tasks]
current_task_id=0

[tasks.data.0]
status="ToDo"
task = {type = "Spawn", loc = [0.0, 0.0, 0.0], color={Rgba=[1.0, 0.0, 0.0, 1.0]}}   # Has to be internally tagged for empty structs to work

[tasks.data.1000]
task = {type = "Despawn"}
